// Generated by gencpp from file robot_msgs/alarm_srvRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ALARM_SRVREQUEST_H
#define ROBOT_MSGS_MESSAGE_ALARM_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct alarm_srvRequest_
{
  typedef alarm_srvRequest_<ContainerAllocator> Type;

  alarm_srvRequest_()
    : volume(0)
    , loop_mode(0)
    , filename(0)
    , fileorder(0)  {
    }
  alarm_srvRequest_(const ContainerAllocator& _alloc)
    : volume(0)
    , loop_mode(0)
    , filename(0)
    , fileorder(0)  {
  (void)_alloc;
    }



   typedef int64_t _volume_type;
  _volume_type volume;

   typedef int64_t _loop_mode_type;
  _loop_mode_type loop_mode;

   typedef int64_t _filename_type;
  _filename_type filename;

   typedef int64_t _fileorder_type;
  _fileorder_type fileorder;





  typedef boost::shared_ptr< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct alarm_srvRequest_

typedef ::robot_msgs::alarm_srvRequest_<std::allocator<void> > alarm_srvRequest;

typedef boost::shared_ptr< ::robot_msgs::alarm_srvRequest > alarm_srvRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::alarm_srvRequest const> alarm_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::alarm_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::alarm_srvRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::alarm_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.volume == rhs.volume &&
    lhs.loop_mode == rhs.loop_mode &&
    lhs.filename == rhs.filename &&
    lhs.fileorder == rhs.fileorder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::alarm_srvRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::alarm_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c3a816de693ddb394770c51f8487b31";
  }

  static const char* value(const ::robot_msgs::alarm_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c3a816de693ddb3ULL;
  static const uint64_t static_value2 = 0x94770c51f8487b31ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/alarm_srvRequest";
  }

  static const char* value(const ::robot_msgs::alarm_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 volume\n"
"int64 loop_mode\n"
"int64 filename\n"
"int64 fileorder\n"
;
  }

  static const char* value(const ::robot_msgs::alarm_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.volume);
      stream.next(m.loop_mode);
      stream.next(m.filename);
      stream.next(m.fileorder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct alarm_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::alarm_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::alarm_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "volume: ";
    Printer<int64_t>::stream(s, indent + "  ", v.volume);
    s << indent << "loop_mode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.loop_mode);
    s << indent << "filename: ";
    Printer<int64_t>::stream(s, indent + "  ", v.filename);
    s << indent << "fileorder: ";
    Printer<int64_t>::stream(s, indent + "  ", v.fileorder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ALARM_SRVREQUEST_H
