// Generated by gencpp from file robot_msgs/alarm_srv.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ALARM_SRV_H
#define ROBOT_MSGS_MESSAGE_ALARM_SRV_H

#include <ros/service_traits.h>


#include <robot_msgs/alarm_srvRequest.h>
#include <robot_msgs/alarm_srvResponse.h>


namespace robot_msgs
{

struct alarm_srv
{

typedef alarm_srvRequest Request;
typedef alarm_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct alarm_srv
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::alarm_srv > {
  static const char* value()
  {
    return "a8f167451be4b108ffefdf3f150aa1b6";
  }

  static const char* value(const ::robot_msgs::alarm_srv&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::alarm_srv > {
  static const char* value()
  {
    return "robot_msgs/alarm_srv";
  }

  static const char* value(const ::robot_msgs::alarm_srv&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::alarm_srvRequest> should match
// service_traits::MD5Sum< ::robot_msgs::alarm_srv >
template<>
struct MD5Sum< ::robot_msgs::alarm_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::alarm_srv >::value();
  }
  static const char* value(const ::robot_msgs::alarm_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::alarm_srvRequest> should match
// service_traits::DataType< ::robot_msgs::alarm_srv >
template<>
struct DataType< ::robot_msgs::alarm_srvRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::alarm_srv >::value();
  }
  static const char* value(const ::robot_msgs::alarm_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::alarm_srvResponse> should match
// service_traits::MD5Sum< ::robot_msgs::alarm_srv >
template<>
struct MD5Sum< ::robot_msgs::alarm_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::alarm_srv >::value();
  }
  static const char* value(const ::robot_msgs::alarm_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::alarm_srvResponse> should match
// service_traits::DataType< ::robot_msgs::alarm_srv >
template<>
struct DataType< ::robot_msgs::alarm_srvResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::alarm_srv >::value();
  }
  static const char* value(const ::robot_msgs::alarm_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ALARM_SRV_H
