// Generated by gencpp from file robot_msgs/cloud_angletims.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_CLOUD_ANGLETIMS_H
#define ROBOT_MSGS_MESSAGE_CLOUD_ANGLETIMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct cloud_angletims_
{
  typedef cloud_angletims_<ContainerAllocator> Type;

  cloud_angletims_()
    : yaw(0.0)
    , pitch(0.0)  {
    }
  cloud_angletims_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::robot_msgs::cloud_angletims_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::cloud_angletims_<ContainerAllocator> const> ConstPtr;

}; // struct cloud_angletims_

typedef ::robot_msgs::cloud_angletims_<std::allocator<void> > cloud_angletims;

typedef boost::shared_ptr< ::robot_msgs::cloud_angletims > cloud_angletimsPtr;
typedef boost::shared_ptr< ::robot_msgs::cloud_angletims const> cloud_angletimsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::cloud_angletims_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::cloud_angletims_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::cloud_angletims_<ContainerAllocator1> & lhs, const ::robot_msgs::cloud_angletims_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::cloud_angletims_<ContainerAllocator1> & lhs, const ::robot_msgs::cloud_angletims_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::cloud_angletims_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::cloud_angletims_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::cloud_angletims_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19ef1e45577dac4da3eff04ddb600a22";
  }

  static const char* value(const ::robot_msgs::cloud_angletims_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19ef1e45577dac4dULL;
  static const uint64_t static_value2 = 0xa3eff04ddb600a22ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/cloud_angletims";
  }

  static const char* value(const ::robot_msgs::cloud_angletims_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"float32 pitch\n"
;
  }

  static const char* value(const ::robot_msgs::cloud_angletims_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cloud_angletims_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::cloud_angletims_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::cloud_angletims_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_CLOUD_ANGLETIMS_H
