// Generated by gencpp from file robot_msgs/Float64Request.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_FLOAT64REQUEST_H
#define ROBOT_MSGS_MESSAGE_FLOAT64REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct Float64Request_
{
  typedef Float64Request_<ContainerAllocator> Type;

  Float64Request_()
    : data(0.0)  {
    }
  Float64Request_(const ContainerAllocator& _alloc)
    : data(0.0)  {
  (void)_alloc;
    }



   typedef double _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robot_msgs::Float64Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Float64Request_<ContainerAllocator> const> ConstPtr;

}; // struct Float64Request_

typedef ::robot_msgs::Float64Request_<std::allocator<void> > Float64Request;

typedef boost::shared_ptr< ::robot_msgs::Float64Request > Float64RequestPtr;
typedef boost::shared_ptr< ::robot_msgs::Float64Request const> Float64RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Float64Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Float64Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Float64Request_<ContainerAllocator1> & lhs, const ::robot_msgs::Float64Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Float64Request_<ContainerAllocator1> & lhs, const ::robot_msgs::Float64Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Float64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Float64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Float64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Float64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Float64Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Float64Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Float64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdb28210bfa9d7c91146260178d9a584";
  }

  static const char* value(const ::robot_msgs::Float64Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdb28210bfa9d7c9ULL;
  static const uint64_t static_value2 = 0x1146260178d9a584ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Float64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Float64Request";
  }

  static const char* value(const ::robot_msgs::Float64Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Float64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data    #Unit: metre\n"
;
  }

  static const char* value(const ::robot_msgs::Float64Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Float64Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float64Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Float64Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Float64Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<double>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_FLOAT64REQUEST_H
