// Generated by gencpp from file robot_msgs/Float64.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_FLOAT64_H
#define ROBOT_MSGS_MESSAGE_FLOAT64_H

#include <ros/service_traits.h>


#include <robot_msgs/Float64Request.h>
#include <robot_msgs/Float64Response.h>


namespace robot_msgs
{

struct Float64
{

typedef Float64Request Request;
typedef Float64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Float64
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Float64 > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::robot_msgs::Float64&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Float64 > {
  static const char* value()
  {
    return "robot_msgs/Float64";
  }

  static const char* value(const ::robot_msgs::Float64&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::Float64Request> should match
// service_traits::MD5Sum< ::robot_msgs::Float64 >
template<>
struct MD5Sum< ::robot_msgs::Float64Request>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Float64 >::value();
  }
  static const char* value(const ::robot_msgs::Float64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::Float64Request> should match
// service_traits::DataType< ::robot_msgs::Float64 >
template<>
struct DataType< ::robot_msgs::Float64Request>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Float64 >::value();
  }
  static const char* value(const ::robot_msgs::Float64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::Float64Response> should match
// service_traits::MD5Sum< ::robot_msgs::Float64 >
template<>
struct MD5Sum< ::robot_msgs::Float64Response>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Float64 >::value();
  }
  static const char* value(const ::robot_msgs::Float64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::Float64Response> should match
// service_traits::DataType< ::robot_msgs::Float64 >
template<>
struct DataType< ::robot_msgs::Float64Response>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Float64 >::value();
  }
  static const char* value(const ::robot_msgs::Float64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_FLOAT64_H
