// Generated by gencpp from file robot_msgs/Gas_alarm.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_GAS_ALARM_H
#define ROBOT_MSGS_MESSAGE_GAS_ALARM_H

#include <ros/service_traits.h>


#include <robot_msgs/Gas_alarmRequest.h>
#include <robot_msgs/Gas_alarmResponse.h>


namespace robot_msgs
{

struct Gas_alarm
{

typedef Gas_alarmRequest Request;
typedef Gas_alarmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gas_alarm
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Gas_alarm > {
  static const char* value()
  {
    return "ac6e499d07c665aef1a9fb36404cb426";
  }

  static const char* value(const ::robot_msgs::Gas_alarm&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Gas_alarm > {
  static const char* value()
  {
    return "robot_msgs/Gas_alarm";
  }

  static const char* value(const ::robot_msgs::Gas_alarm&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::Gas_alarmRequest> should match
// service_traits::MD5Sum< ::robot_msgs::Gas_alarm >
template<>
struct MD5Sum< ::robot_msgs::Gas_alarmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Gas_alarm >::value();
  }
  static const char* value(const ::robot_msgs::Gas_alarmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::Gas_alarmRequest> should match
// service_traits::DataType< ::robot_msgs::Gas_alarm >
template<>
struct DataType< ::robot_msgs::Gas_alarmRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Gas_alarm >::value();
  }
  static const char* value(const ::robot_msgs::Gas_alarmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::Gas_alarmResponse> should match
// service_traits::MD5Sum< ::robot_msgs::Gas_alarm >
template<>
struct MD5Sum< ::robot_msgs::Gas_alarmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Gas_alarm >::value();
  }
  static const char* value(const ::robot_msgs::Gas_alarmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::Gas_alarmResponse> should match
// service_traits::DataType< ::robot_msgs::Gas_alarm >
template<>
struct DataType< ::robot_msgs::Gas_alarmResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Gas_alarm >::value();
  }
  static const char* value(const ::robot_msgs::Gas_alarmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_GAS_ALARM_H
