// Generated by gencpp from file robot_msgs/Gas_alarmRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_GAS_ALARMREQUEST_H
#define ROBOT_MSGS_MESSAGE_GAS_ALARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct Gas_alarmRequest_
{
  typedef Gas_alarmRequest_<ContainerAllocator> Type;

  Gas_alarmRequest_()
    : start(false)  {
    }
  Gas_alarmRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Gas_alarmRequest_

typedef ::robot_msgs::Gas_alarmRequest_<std::allocator<void> > Gas_alarmRequest;

typedef boost::shared_ptr< ::robot_msgs::Gas_alarmRequest > Gas_alarmRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::Gas_alarmRequest const> Gas_alarmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Gas_alarmRequest";
  }

  static const char* value(const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gas_alarmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Gas_alarmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Gas_alarmRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_GAS_ALARMREQUEST_H
