// Generated by gencpp from file robot_msgs/Gas_alarmResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_GAS_ALARMRESPONSE_H
#define ROBOT_MSGS_MESSAGE_GAS_ALARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct Gas_alarmResponse_
{
  typedef Gas_alarmResponse_<ContainerAllocator> Type;

  Gas_alarmResponse_()
    : result(0)  {
    }
  Gas_alarmResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Gas_alarmResponse_

typedef ::robot_msgs::Gas_alarmResponse_<std::allocator<void> > Gas_alarmResponse;

typedef boost::shared_ptr< ::robot_msgs::Gas_alarmResponse > Gas_alarmResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::Gas_alarmResponse const> Gas_alarmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Gas_alarmResponse";
  }

  static const char* value(const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
;
  }

  static const char* value(const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gas_alarmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Gas_alarmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Gas_alarmResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_GAS_ALARMRESPONSE_H
