// Generated by gencpp from file robot_msgs/nav_goal.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAV_GOAL_H
#define ROBOT_MSGS_MESSAGE_NAV_GOAL_H

#include <ros/service_traits.h>


#include <robot_msgs/nav_goalRequest.h>
#include <robot_msgs/nav_goalResponse.h>


namespace robot_msgs
{

struct nav_goal
{

typedef nav_goalRequest Request;
typedef nav_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_goal
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::nav_goal > {
  static const char* value()
  {
    return "6f7829491dcb15f3121622bb0d29b3ea";
  }

  static const char* value(const ::robot_msgs::nav_goal&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::nav_goal > {
  static const char* value()
  {
    return "robot_msgs/nav_goal";
  }

  static const char* value(const ::robot_msgs::nav_goal&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::nav_goalRequest> should match
// service_traits::MD5Sum< ::robot_msgs::nav_goal >
template<>
struct MD5Sum< ::robot_msgs::nav_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::nav_goal >::value();
  }
  static const char* value(const ::robot_msgs::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::nav_goalRequest> should match
// service_traits::DataType< ::robot_msgs::nav_goal >
template<>
struct DataType< ::robot_msgs::nav_goalRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::nav_goal >::value();
  }
  static const char* value(const ::robot_msgs::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::nav_goalResponse> should match
// service_traits::MD5Sum< ::robot_msgs::nav_goal >
template<>
struct MD5Sum< ::robot_msgs::nav_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::nav_goal >::value();
  }
  static const char* value(const ::robot_msgs::nav_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::nav_goalResponse> should match
// service_traits::DataType< ::robot_msgs::nav_goal >
template<>
struct DataType< ::robot_msgs::nav_goalResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::nav_goal >::value();
  }
  static const char* value(const ::robot_msgs::nav_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAV_GOAL_H
