// Generated by gencpp from file robot_msgs/nav_goalResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAV_GOALRESPONSE_H
#define ROBOT_MSGS_MESSAGE_NAV_GOALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct nav_goalResponse_
{
  typedef nav_goalResponse_<ContainerAllocator> Type;

  nav_goalResponse_()
    : th(0)
    , success(0)
    , message()  {
    }
  nav_goalResponse_(const ContainerAllocator& _alloc)
    : th(0)
    , success(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _th_type;
  _th_type th;

   typedef int8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::robot_msgs::nav_goalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::nav_goalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nav_goalResponse_

typedef ::robot_msgs::nav_goalResponse_<std::allocator<void> > nav_goalResponse;

typedef boost::shared_ptr< ::robot_msgs::nav_goalResponse > nav_goalResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::nav_goalResponse const> nav_goalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::nav_goalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::nav_goalResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::nav_goalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.th == rhs.th &&
    lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::nav_goalResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::nav_goalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::nav_goalResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::nav_goalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::nav_goalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "130d3c324d2926d74adbb83f071eb265";
  }

  static const char* value(const ::robot_msgs::nav_goalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x130d3c324d2926d7ULL;
  static const uint64_t static_value2 = 0x4adbb83f071eb265ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/nav_goalResponse";
  }

  static const char* value(const ::robot_msgs::nav_goalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 th\n"
"int8 success\n"
"string message\n"
;
  }

  static const char* value(const ::robot_msgs::nav_goalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.th);
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_goalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::nav_goalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::nav_goalResponse_<ContainerAllocator>& v)
  {
    s << indent << "th: ";
    Printer<int32_t>::stream(s, indent + "  ", v.th);
    s << indent << "success: ";
    Printer<int8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAV_GOALRESPONSE_H
