// Generated by gencpp from file robot_msgs/nav_goalRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_NAV_GOALREQUEST_H
#define ROBOT_MSGS_MESSAGE_NAV_GOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct nav_goalRequest_
{
  typedef nav_goalRequest_<ContainerAllocator> Type;

  nav_goalRequest_()
    : x(0.0)
    , y(0.0)
    , th(0.0)  {
    }
  nav_goalRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::robot_msgs::nav_goalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::nav_goalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nav_goalRequest_

typedef ::robot_msgs::nav_goalRequest_<std::allocator<void> > nav_goalRequest;

typedef boost::shared_ptr< ::robot_msgs::nav_goalRequest > nav_goalRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::nav_goalRequest const> nav_goalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::nav_goalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::nav_goalRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::nav_goalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::nav_goalRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::nav_goalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::nav_goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::nav_goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::nav_goalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "000e435776f4fd6ba555d25d7a61ed8f";
  }

  static const char* value(const ::robot_msgs::nav_goalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x000e435776f4fd6bULL;
  static const uint64_t static_value2 = 0xa555d25d7a61ed8fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/nav_goalRequest";
  }

  static const char* value(const ::robot_msgs::nav_goalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 th\n"
;
  }

  static const char* value(const ::robot_msgs::nav_goalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_goalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::nav_goalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::nav_goalRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "th: ";
    Printer<double>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_NAV_GOALREQUEST_H
