// Generated by gencpp from file robot_msgs/PtzPresetRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_PTZPRESETREQUEST_H
#define ROBOT_MSGS_MESSAGE_PTZPRESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct PtzPresetRequest_
{
  typedef PtzPresetRequest_<ContainerAllocator> Type;

  PtzPresetRequest_()
    : yaw(0.0)
    , pitch(0.0)  {
    }
  PtzPresetRequest_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PtzPresetRequest_

typedef ::robot_msgs::PtzPresetRequest_<std::allocator<void> > PtzPresetRequest;

typedef boost::shared_ptr< ::robot_msgs::PtzPresetRequest > PtzPresetRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::PtzPresetRequest const> PtzPresetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::PtzPresetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::PtzPresetRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::PtzPresetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::PtzPresetRequest_<ContainerAllocator1> & lhs, const ::robot_msgs::PtzPresetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84eddaf18b6b9df47b605419a0572436";
  }

  static const char* value(const ::robot_msgs::PtzPresetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84eddaf18b6b9df4ULL;
  static const uint64_t static_value2 = 0x7b605419a0572436ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/PtzPresetRequest";
  }

  static const char* value(const ::robot_msgs::PtzPresetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 yaw\n"
"float64 pitch\n"
;
  }

  static const char* value(const ::robot_msgs::PtzPresetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PtzPresetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::PtzPresetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::PtzPresetRequest_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_PTZPRESETREQUEST_H
