// Generated by gencpp from file robot_msgs/PtzPreset.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_PTZPRESET_H
#define ROBOT_MSGS_MESSAGE_PTZPRESET_H

#include <ros/service_traits.h>


#include <robot_msgs/PtzPresetRequest.h>
#include <robot_msgs/PtzPresetResponse.h>


namespace robot_msgs
{

struct PtzPreset
{

typedef PtzPresetRequest Request;
typedef PtzPresetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PtzPreset
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::PtzPreset > {
  static const char* value()
  {
    return "7b8a23f3742a103da89bd600506ecc86";
  }

  static const char* value(const ::robot_msgs::PtzPreset&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::PtzPreset > {
  static const char* value()
  {
    return "robot_msgs/PtzPreset";
  }

  static const char* value(const ::robot_msgs::PtzPreset&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::PtzPresetRequest> should match
// service_traits::MD5Sum< ::robot_msgs::PtzPreset >
template<>
struct MD5Sum< ::robot_msgs::PtzPresetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::PtzPreset >::value();
  }
  static const char* value(const ::robot_msgs::PtzPresetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::PtzPresetRequest> should match
// service_traits::DataType< ::robot_msgs::PtzPreset >
template<>
struct DataType< ::robot_msgs::PtzPresetRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::PtzPreset >::value();
  }
  static const char* value(const ::robot_msgs::PtzPresetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::PtzPresetResponse> should match
// service_traits::MD5Sum< ::robot_msgs::PtzPreset >
template<>
struct MD5Sum< ::robot_msgs::PtzPresetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::PtzPreset >::value();
  }
  static const char* value(const ::robot_msgs::PtzPresetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::PtzPresetResponse> should match
// service_traits::DataType< ::robot_msgs::PtzPreset >
template<>
struct DataType< ::robot_msgs::PtzPresetResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::PtzPreset >::value();
  }
  static const char* value(const ::robot_msgs::PtzPresetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_PTZPRESET_H
