// Generated by gencpp from file robot_msgs/recognition_scaleResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_RECOGNITION_SCALERESPONSE_H
#define ROBOT_MSGS_MESSAGE_RECOGNITION_SCALERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct recognition_scaleResponse_
{
  typedef recognition_scaleResponse_<ContainerAllocator> Type;

  recognition_scaleResponse_()
    : image_path()
    , result(0.0)
    , time()  {
    }
  recognition_scaleResponse_(const ContainerAllocator& _alloc)
    : image_path(_alloc)
    , result(0.0)
    , time(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_path_type;
  _image_path_type image_path;

   typedef double _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct recognition_scaleResponse_

typedef ::robot_msgs::recognition_scaleResponse_<std::allocator<void> > recognition_scaleResponse;

typedef boost::shared_ptr< ::robot_msgs::recognition_scaleResponse > recognition_scaleResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::recognition_scaleResponse const> recognition_scaleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.image_path == rhs.image_path &&
    lhs.result == rhs.result &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator1> & lhs, const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cfa4c62e2f8f57ddf8e725449d7973d";
  }

  static const char* value(const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cfa4c62e2f8f57dULL;
  static const uint64_t static_value2 = 0xdf8e725449d7973dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/recognition_scaleResponse";
  }

  static const char* value(const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string image_path\n"
"float64 result\n"
"string time\n"
;
  }

  static const char* value(const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
      stream.next(m.result);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recognition_scaleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::recognition_scaleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::recognition_scaleResponse_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_path);
    s << indent << "result: ";
    Printer<double>::stream(s, indent + "  ", v.result);
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_RECOGNITION_SCALERESPONSE_H
