// Generated by gencpp from file robot_msgs/recognition_scale.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_RECOGNITION_SCALE_H
#define ROBOT_MSGS_MESSAGE_RECOGNITION_SCALE_H

#include <ros/service_traits.h>


#include <robot_msgs/recognition_scaleRequest.h>
#include <robot_msgs/recognition_scaleResponse.h>


namespace robot_msgs
{

struct recognition_scale
{

typedef recognition_scaleRequest Request;
typedef recognition_scaleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recognition_scale
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::recognition_scale > {
  static const char* value()
  {
    return "517170519764f280df543ca1d4bff866";
  }

  static const char* value(const ::robot_msgs::recognition_scale&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::recognition_scale > {
  static const char* value()
  {
    return "robot_msgs/recognition_scale";
  }

  static const char* value(const ::robot_msgs::recognition_scale&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::recognition_scaleRequest> should match
// service_traits::MD5Sum< ::robot_msgs::recognition_scale >
template<>
struct MD5Sum< ::robot_msgs::recognition_scaleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::recognition_scale >::value();
  }
  static const char* value(const ::robot_msgs::recognition_scaleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::recognition_scaleRequest> should match
// service_traits::DataType< ::robot_msgs::recognition_scale >
template<>
struct DataType< ::robot_msgs::recognition_scaleRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::recognition_scale >::value();
  }
  static const char* value(const ::robot_msgs::recognition_scaleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::recognition_scaleResponse> should match
// service_traits::MD5Sum< ::robot_msgs::recognition_scale >
template<>
struct MD5Sum< ::robot_msgs::recognition_scaleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::recognition_scale >::value();
  }
  static const char* value(const ::robot_msgs::recognition_scaleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::recognition_scaleResponse> should match
// service_traits::DataType< ::robot_msgs::recognition_scale >
template<>
struct DataType< ::robot_msgs::recognition_scaleResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::recognition_scale >::value();
  }
  static const char* value(const ::robot_msgs::recognition_scaleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_RECOGNITION_SCALE_H
