// Generated by gencpp from file robot_msgs/robot_pose.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOT_POSE_H
#define ROBOT_MSGS_MESSAGE_ROBOT_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct robot_pose_
{
  typedef robot_pose_<ContainerAllocator> Type;

  robot_pose_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  robot_pose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::robot_msgs::robot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::robot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct robot_pose_

typedef ::robot_msgs::robot_pose_<std::allocator<void> > robot_pose;

typedef boost::shared_ptr< ::robot_msgs::robot_pose > robot_posePtr;
typedef boost::shared_ptr< ::robot_msgs::robot_pose const> robot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::robot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::robot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::robot_pose_<ContainerAllocator1> & lhs, const ::robot_msgs::robot_pose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::robot_pose_<ContainerAllocator1> & lhs, const ::robot_msgs::robot_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47802147045815b06859cca542c21d31";
  }

  static const char* value(const ::robot_msgs::robot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47802147045815b0ULL;
  static const uint64_t static_value2 = 0x6859cca542c21d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/robot_pose";
  }

  static const char* value(const ::robot_msgs::robot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::robot_msgs::robot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::robot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::robot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::robot_pose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOT_POSE_H
