// Generated by gencpp from file robot_msgs/setint16Request.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SETINT16REQUEST_H
#define ROBOT_MSGS_MESSAGE_SETINT16REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct setint16Request_
{
  typedef setint16Request_<ContainerAllocator> Type;

  setint16Request_()
    : data(0)  {
    }
  setint16Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int64_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robot_msgs::setint16Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::setint16Request_<ContainerAllocator> const> ConstPtr;

}; // struct setint16Request_

typedef ::robot_msgs::setint16Request_<std::allocator<void> > setint16Request;

typedef boost::shared_ptr< ::robot_msgs::setint16Request > setint16RequestPtr;
typedef boost::shared_ptr< ::robot_msgs::setint16Request const> setint16RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::setint16Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::setint16Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::setint16Request_<ContainerAllocator1> & lhs, const ::robot_msgs::setint16Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::setint16Request_<ContainerAllocator1> & lhs, const ::robot_msgs::setint16Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::setint16Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::setint16Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::setint16Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::setint16Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::setint16Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::setint16Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::setint16Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34add168574510e6e17f5d23ecc077ef";
  }

  static const char* value(const ::robot_msgs::setint16Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34add168574510e6ULL;
  static const uint64_t static_value2 = 0xe17f5d23ecc077efULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::setint16Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/setint16Request";
  }

  static const char* value(const ::robot_msgs::setint16Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::setint16Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 data # e.g. for hardware enabling / disabling\n"
;
  }

  static const char* value(const ::robot_msgs::setint16Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::setint16Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setint16Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::setint16Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::setint16Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SETINT16REQUEST_H
