// Generated by gencpp from file robot_msgs/temp_detection.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_TEMP_DETECTION_H
#define ROBOT_MSGS_MESSAGE_TEMP_DETECTION_H

#include <ros/service_traits.h>


#include <robot_msgs/temp_detectionRequest.h>
#include <robot_msgs/temp_detectionResponse.h>


namespace robot_msgs
{

struct temp_detection
{

typedef temp_detectionRequest Request;
typedef temp_detectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct temp_detection
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::temp_detection > {
  static const char* value()
  {
    return "fbe2b0e6d586ba7b0e807a33c06658ad";
  }

  static const char* value(const ::robot_msgs::temp_detection&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::temp_detection > {
  static const char* value()
  {
    return "robot_msgs/temp_detection";
  }

  static const char* value(const ::robot_msgs::temp_detection&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::temp_detectionRequest> should match
// service_traits::MD5Sum< ::robot_msgs::temp_detection >
template<>
struct MD5Sum< ::robot_msgs::temp_detectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::temp_detection >::value();
  }
  static const char* value(const ::robot_msgs::temp_detectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::temp_detectionRequest> should match
// service_traits::DataType< ::robot_msgs::temp_detection >
template<>
struct DataType< ::robot_msgs::temp_detectionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::temp_detection >::value();
  }
  static const char* value(const ::robot_msgs::temp_detectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::temp_detectionResponse> should match
// service_traits::MD5Sum< ::robot_msgs::temp_detection >
template<>
struct MD5Sum< ::robot_msgs::temp_detectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::temp_detection >::value();
  }
  static const char* value(const ::robot_msgs::temp_detectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::temp_detectionResponse> should match
// service_traits::DataType< ::robot_msgs::temp_detection >
template<>
struct DataType< ::robot_msgs::temp_detectionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::temp_detection >::value();
  }
  static const char* value(const ::robot_msgs::temp_detectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_TEMP_DETECTION_H
