; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude centerResult.msg.html

(cl:defclass <centerResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0))
)

(cl:defclass centerResult (<centerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <centerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'centerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<centerResult> is deprecated: use robot_msgs-msg:centerResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <centerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:result-val is deprecated.  Use robot_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <centerResult>) ostream)
  "Serializes a message object of type '<centerResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <centerResult>) istream)
  "Deserializes a message object of type '<centerResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<centerResult>)))
  "Returns string type for a message object of type '<centerResult>"
  "robot_msgs/centerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'centerResult)))
  "Returns string type for a message object of type 'centerResult"
  "robot_msgs/centerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<centerResult>)))
  "Returns md5sum for a message object of type '<centerResult>"
  "25458147911545c320c4c0a299eff763")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'centerResult)))
  "Returns md5sum for a message object of type 'centerResult"
  "25458147911545c320c4c0a299eff763")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<centerResult>)))
  "Returns full string definition for message of type '<centerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 result    #动作完成或暂停时的输出结果~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'centerResult)))
  "Returns full string definition for message of type 'centerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 result    #动作完成或暂停时的输出结果~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <centerResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <centerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'centerResult
    (cl:cons ':result (result msg))
))
