; Auto-generated. Do not edit!


(cl:in-package robot_msgs-msg)


;//! \htmlinclude centerGoal.msg.html

(cl:defclass <centerGoal> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:fixnum
    :initform 0)
   (point_number
    :reader point_number
    :initarg :point_number
    :type cl:fixnum
    :initform 0))
)

(cl:defclass centerGoal (<centerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <centerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'centerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msgs-msg:<centerGoal> is deprecated: use robot_msgs-msg:centerGoal instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <centerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:state-val is deprecated.  Use robot_msgs-msg:state instead.")
  (state m))

(cl:ensure-generic-function 'point_number-val :lambda-list '(m))
(cl:defmethod point_number-val ((m <centerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msgs-msg:point_number-val is deprecated.  Use robot_msgs-msg:point_number instead.")
  (point_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <centerGoal>) ostream)
  "Serializes a message object of type '<centerGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'point_number)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'point_number)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <centerGoal>) istream)
  "Deserializes a message object of type '<centerGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'point_number)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'point_number)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<centerGoal>)))
  "Returns string type for a message object of type '<centerGoal>"
  "robot_msgs/centerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'centerGoal)))
  "Returns string type for a message object of type 'centerGoal"
  "robot_msgs/centerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<centerGoal>)))
  "Returns md5sum for a message object of type '<centerGoal>"
  "8049b2c79c10b7ff9a3f5b6430379d8e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'centerGoal)))
  "Returns md5sum for a message object of type 'centerGoal"
  "8049b2c79c10b7ff9a3f5b6430379d8e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<centerGoal>)))
  "Returns full string definition for message of type '<centerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 state #开始~%uint16 point_number #执行动作的点位~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'centerGoal)))
  "Returns full string definition for message of type 'centerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 state #开始~%uint16 point_number #执行动作的点位~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <centerGoal>))
  (cl:+ 0
     1
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <centerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'centerGoal
    (cl:cons ':state (state msg))
    (cl:cons ':point_number (point_number msg))
))
