# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/cloud_control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cloud_control(genpy.Message):
  _md5sum = "8a0daeeb4fd2f539306a2fb5b806e7f7"
  _type = "robot_msgs/cloud_control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string direction
float64 angular_percent
bool zero
bool scrub
bool light"""
  __slots__ = ['direction','angular_percent','zero','scrub','light']
  _slot_types = ['string','float64','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       direction,angular_percent,zero,scrub,light

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cloud_control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.direction is None:
        self.direction = ''
      if self.angular_percent is None:
        self.angular_percent = 0.
      if self.zero is None:
        self.zero = False
      if self.scrub is None:
        self.scrub = False
      if self.light is None:
        self.light = False
    else:
      self.direction = ''
      self.angular_percent = 0.
      self.zero = False
      self.scrub = False
      self.light = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d3B().pack(_x.angular_percent, _x.zero, _x.scrub, _x.light))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.direction = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.angular_percent, _x.zero, _x.scrub, _x.light,) = _get_struct_d3B().unpack(str[start:end])
      self.zero = bool(self.zero)
      self.scrub = bool(self.scrub)
      self.light = bool(self.light)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d3B().pack(_x.angular_percent, _x.zero, _x.scrub, _x.light))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.direction = str[start:end]
      _x = self
      start = end
      end += 11
      (_x.angular_percent, _x.zero, _x.scrub, _x.light,) = _get_struct_d3B().unpack(str[start:end])
      self.zero = bool(self.zero)
      self.scrub = bool(self.scrub)
      self.light = bool(self.light)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d3B = None
def _get_struct_d3B():
    global _struct_d3B
    if _struct_d3B is None:
        _struct_d3B = struct.Struct("<d3B")
    return _struct_d3B
