# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/dgps.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class dgps(genpy.Message):
  _md5sum = "c990cbed4ebc800837d6877b60880af5"
  _type = "robot_msgs/dgps"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 z
float64 roll
float64 pitch
float64 yaw
float64 by_pose0
float64 by_pose1
float64 sin_th_q1
float64 cos_th_q1
float64 sin_th
float64 cos_th
float64 bbyyy
"""
  __slots__ = ['x','y','z','roll','pitch','yaw','by_pose0','by_pose1','sin_th_q1','cos_th_q1','sin_th','cos_th','bbyyy']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,roll,pitch,yaw,by_pose0,by_pose1,sin_th_q1,cos_th_q1,sin_th,cos_th,bbyyy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dgps, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.by_pose0 is None:
        self.by_pose0 = 0.
      if self.by_pose1 is None:
        self.by_pose1 = 0.
      if self.sin_th_q1 is None:
        self.sin_th_q1 = 0.
      if self.cos_th_q1 is None:
        self.cos_th_q1 = 0.
      if self.sin_th is None:
        self.sin_th = 0.
      if self.cos_th is None:
        self.cos_th = 0.
      if self.bbyyy is None:
        self.bbyyy = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.by_pose0 = 0.
      self.by_pose1 = 0.
      self.sin_th_q1 = 0.
      self.cos_th_q1 = 0.
      self.sin_th = 0.
      self.cos_th = 0.
      self.bbyyy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.by_pose0, _x.by_pose1, _x.sin_th_q1, _x.cos_th_q1, _x.sin_th, _x.cos_th, _x.bbyyy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.by_pose0, _x.by_pose1, _x.sin_th_q1, _x.cos_th_q1, _x.sin_th, _x.cos_th, _x.bbyyy,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_13d().pack(_x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.by_pose0, _x.by_pose1, _x.sin_th_q1, _x.cos_th_q1, _x.sin_th, _x.cos_th, _x.bbyyy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 104
      (_x.x, _x.y, _x.z, _x.roll, _x.pitch, _x.yaw, _x.by_pose0, _x.by_pose1, _x.sin_th_q1, _x.cos_th_q1, _x.sin_th, _x.cos_th, _x.bbyyy,) = _get_struct_13d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_13d = None
def _get_struct_13d():
    global _struct_13d
    if _struct_13d is None:
        _struct_13d = struct.Struct("<13d")
    return _struct_13d
