// Generated by gencpp from file alarm_device/alarm_srvResponse.msg
// DO NOT EDIT!


#ifndef ALARM_DEVICE_MESSAGE_ALARM_SRVRESPONSE_H
#define ALARM_DEVICE_MESSAGE_ALARM_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alarm_device
{
template <class ContainerAllocator>
struct alarm_srvResponse_
{
  typedef alarm_srvResponse_<ContainerAllocator> Type;

  alarm_srvResponse_()
    {
    }
  alarm_srvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::alarm_device::alarm_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alarm_device::alarm_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct alarm_srvResponse_

typedef ::alarm_device::alarm_srvResponse_<std::allocator<void> > alarm_srvResponse;

typedef boost::shared_ptr< ::alarm_device::alarm_srvResponse > alarm_srvResponsePtr;
typedef boost::shared_ptr< ::alarm_device::alarm_srvResponse const> alarm_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alarm_device::alarm_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace alarm_device

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alarm_device::alarm_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alarm_device::alarm_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alarm_device::alarm_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::alarm_device::alarm_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alarm_device/alarm_srvResponse";
  }

  static const char* value(const ::alarm_device::alarm_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::alarm_device::alarm_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct alarm_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alarm_device::alarm_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::alarm_device::alarm_srvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ALARM_DEVICE_MESSAGE_ALARM_SRVRESPONSE_H
