// Generated by gencpp from file alarm_device/alarm_srv.msg
// DO NOT EDIT!


#ifndef ALARM_DEVICE_MESSAGE_ALARM_SRV_H
#define ALARM_DEVICE_MESSAGE_ALARM_SRV_H

#include <ros/service_traits.h>


#include <alarm_device/alarm_srvRequest.h>
#include <alarm_device/alarm_srvResponse.h>


namespace alarm_device
{

struct alarm_srv
{

typedef alarm_srvRequest Request;
typedef alarm_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct alarm_srv
} // namespace alarm_device


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::alarm_device::alarm_srv > {
  static const char* value()
  {
    return "eba3e264b7446975115540c352322db3";
  }

  static const char* value(const ::alarm_device::alarm_srv&) { return value(); }
};

template<>
struct DataType< ::alarm_device::alarm_srv > {
  static const char* value()
  {
    return "alarm_device/alarm_srv";
  }

  static const char* value(const ::alarm_device::alarm_srv&) { return value(); }
};


// service_traits::MD5Sum< ::alarm_device::alarm_srvRequest> should match
// service_traits::MD5Sum< ::alarm_device::alarm_srv >
template<>
struct MD5Sum< ::alarm_device::alarm_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::alarm_device::alarm_srv >::value();
  }
  static const char* value(const ::alarm_device::alarm_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::alarm_device::alarm_srvRequest> should match
// service_traits::DataType< ::alarm_device::alarm_srv >
template<>
struct DataType< ::alarm_device::alarm_srvRequest>
{
  static const char* value()
  {
    return DataType< ::alarm_device::alarm_srv >::value();
  }
  static const char* value(const ::alarm_device::alarm_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::alarm_device::alarm_srvResponse> should match
// service_traits::MD5Sum< ::alarm_device::alarm_srv >
template<>
struct MD5Sum< ::alarm_device::alarm_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::alarm_device::alarm_srv >::value();
  }
  static const char* value(const ::alarm_device::alarm_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::alarm_device::alarm_srvResponse> should match
// service_traits::DataType< ::alarm_device::alarm_srv >
template<>
struct DataType< ::alarm_device::alarm_srvResponse>
{
  static const char* value()
  {
    return DataType< ::alarm_device::alarm_srv >::value();
  }
  static const char* value(const ::alarm_device::alarm_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALARM_DEVICE_MESSAGE_ALARM_SRV_H
